### ISSUE TITLE
Is it possible to run `docker build` and `docker push` inside a container of this image?

### ISSUE THREAD

**Issue by grahovam** [sameersbn/docker-gitlab-ci-multi-runner#12]
I would like to build and push docker images inside a docker container. I want to setup a CI-Environment where docker images are being built and pushed after a git commit has been pushed to gitlab. 

I've read about using Docker inside Docker, but since i just want to build and push, this seems to be a little overweight and there is important security issues to be considered (http://jpetazzo.github.io/2015/09/03/do-not-use-docker-in-docker-for-ci/)

Is there a more straight forward way to do this?

Gitlab Version: CE 8.2.3 
Docker Version: 1.9.1

Thank you very much

Edit: Excuse me, I didn't realize that #5 talks about just that.

**Comment by sameersbn** [comment]
@grahovam I think you can expose the host docker binary and socket to the runner and build/push the images. see #5 to know how you can expose the host docker binary and socket to your runner. But beware, there is still a huge security risk with this method as well since a user would be able to mount the rootfs of the host as a volume in a container and do as they please.

**Comment by grahovam** [comment]
I see the security risk. But it is not more risky than running a gitlab runner directly in my VM instead of in a container, because there the rootfs would be mounted from the beginning, or am I making a mistake here?

**Comment by sameersbn** [comment]
that is true. if you are creating a VM for the sole purpose of a runner then it should be mostly fine.

**Comment by grahovam** [comment]
It seems like it's still not working. I create a container using

```bash
docker run -d \
  --name gitlab-runner \
  --restart=always \
  --volume /srv/docker/gitlab/runner/:/home/gitlab_ci_multi_runner/data \
  --volume /var/run/docker.sock:/run/docker.sock \
  --volume $(which docker):/bin/docker \
  --env='CI_SERVER_URL=https://gitlab.myserver.de/ci' \
  --env='RUNNER_TOKEN=mytoken' \
  --env='RUNNER_DESCRIPTION=myrunner' \
  --env='RUNNER_EXECUTOR=docker' \
  sameersbn/gitlab-ci-multi-runner
```

and then i go into the container using

```bash
docker exec -it gitlab-runner bash
```

and if i enter ```docker``` i get

```bash
docker: error while loading shared libraries: libapparmor.so.1: cannot open shared object file: No such file or directory
```

**Comment by sameersbn** [comment]
you can add do a `apt-get install libapparmor1` in the image or add the following to the run command.

```
--volume /usr/lib/x86_64-linux-gnu/libapparmor.so.1:/usr/lib/x86_64-linux-gnu/libapparmor.so.1:ro \
--volume /usr/lib/x86_64-linux-gnu/libapparmor.so.1.1.0:/usr/lib/x86_64-linux-gnu/libapparmor.so.1.1.0:ro \
```

I will add the libapparmor1 in future releases.

**Comment by grahovam** [comment]
Alright, thank you very much.

**Comment by sameersbn** [comment]
have added `libapparmor1` in the `latest` build
