### ISSUE TITLE
server certificate verification failed - Let's Encrypt Certificate 

### ISSUE THREAD

**Issue by meronimo** [sameersbn/docker-gitlab-ci-multi-runner#40]
Hello

i'm running GitLab on my Synology with a Let's Encrypt Certificate.

When i start my pipeline procress i get the following error message.
```shell
gitlab-ci-multi-runner 1.1.4 (9e2fd1a)
Using Shell executor...
Running on 1567fe55aaf2...
Cloning repository...
Cloning into '/home/gitlab_ci_multi_runner/data/builds/4e31f1b9/0/user/test'...
fatal: unable to access 'https://gitlab-ci-token:xxxxxxxxxxxxxxxxxxxx@ds.domain.de:30000/user/test.git/': server certificate verification failed. CAfile: /home/gitlab_ci_multi_runner/data/builds/4e31f1b9/0/user/test.tmp/GIT_SSL_CAINFO CRLfile: none

ERROR: Build failed: exit status 1
```

Let's Encrypt provides:
cert.pem
chain.pem
privkey.pem

How can i provide gitlab runner the correct certificate format?

**Comment by Zaroastre** [comment]
Hello,
I have exactly the same issue ! 
My GitLab virtual server is running behind a Nginx reverse proxy.
I've request a wildcard certificate from Let's Encrypt for my domain name. The certificate is installed on the reverse proxy.

My error is : 
`Cloning into '/builds/projects/test'...
fatal: unable to access 'http://gitlab-ci-token:xxxxxxxxxxxxxxxxxxxx@gitlab.my-domain.ex/projects/test.git/': server certificate verification failed. CAfile: none CRLfile: none
ERROR: Job failed: exit code 1`

How can I solve my problem ?

Thank you !

**Comment by TT2N9** [comment]
Hi All,
I got the same issue, 
Could u do a feddback with your solution please ?

Running with gitlab-runner 11.8.0 (4745a6f3)
  on DGTDEV2 Yt5_Zc7D
Using Shell executor...
Running on DGTDEV2...
00:00
Fetching changes...
00:00
HEAD is now at df264e0b31 [BCIDEV-13737]Fix cache clearing from admin
fatal: unable to access 'https://gitlab-ci-token:xxxxxxxxxxxxxxxxxxxx@git.domain.com/JadeoFrance/core_frontend.git/': server certificate verification failed. CAfile: /home/gitlab-runner/builds/Yt5_Zc7D/0/domain/core_frontend.tmp/CI_SERVER_TLS_CA_FILE CRLfile: none
ERROR: Job failed: exit status 1
