### ISSUE TITLE
Adding curl

### ISSUE THREAD

**Issue by Maescool** [sameersbn/docker-gitlab-ci-multi-runner#8]
Hi,
Big fan of your images! <3

I wonder if you could install curl?
This is used for the triggers gitlab has, to trigger a build from a build
https://about.gitlab.com/2015/08/22/gitlab-7-14-released/

Thanks!

**Comment by sameersbn** [comment]
This image is meant to be a base image for your runners which means you use this image to base your runner images. As such in your runner image you can install any package you desire/

**Comment by sameersbn** [comment]
p.s. curl is being installed in the image.
